### ISSUE TITLE
Google creds required?

### ISSUE THREAD

**Issue by cjohnson-bf** [lavalamp-/ws-docker-community#3]
The dockerfile for backend seems to want GCE creds? I tried commenting these lines out, but then scripts/run-api-tests.sh fails. Should I just ignore those test results, or is google required?

```
$ cat dockerfiles/backend-base.dockerfile
...
ADD secrets/gce.json /ws-backend/files/gce.json

ENV GOOGLE_APPLICATION_CREDENTIALS /ws-backend/files/gce.json
...
```

Thanks again!

**Comment by lavalamp-** [comment]
Hey @d0teater - so I wrote some stuff that enables Web Sight to use both GCE and S3, and getting all of that to work with GCE is kind of a hassle. Whether or not you're using GCE, Docker will need to move a `gce.json` file into the container.

I believe I updated the README but I'll double check. In the mean time all you have to do is (from the root ws-docker-community directory):

```
touch secrets/gce.json
```

It will then be an empty file and Docker won't complain, and if you have Web Sight configured to use S3 then the contents of the empty gce.json file are never used! Just make sure to specify that your data storage backend is S3 in `tasknode.cfg`:

```
[Storage]

storage_platform = aws
```

**Comment by cjohnson-bf** [comment]
That works, thanks.
